### PR TITLE
Convert build tooling to rockcraft

### PR DESCRIPTION
**Pull request by jardon**
## Issue

The original build process utilizes docker to build the OCI image.

## Solution

The build process should use `rockcraft` to build the OCI image to match our other products.

## Context

[rockcraft](https://github.com/canonical/rockcraft)
[mysql router 8.0 docs](https://dev.mysql.com/doc/mysql-router/8.0/en/)

## Release Notes

Add rockcraft.yaml and supporting CI.

## Testing

None as this is a draft :)

### CODE REVIEW

**Comment by jardon** [comment]
@taurus-forever this PR includes all the changes from LP.  Whenever you're done configuring the syncing, the PR will be left with only a single commit and can be moved to `Ready to Review`

**Comment by taurus-forever** [comment]
> @taurus-forever this PR includes all the changes from LP. Whenever you're done configuring the syncing, the PR will be left with only a single commit and can be moved to `Ready to Review`

Tnx! WIP for sync. ETA: the next 24 hours. :-D

**Comment by jardon** [comment]
@taurus-forever can you clarify which branch this should be going into and why the default doesnt seem to be in line with `8.0_22.04`?

**Comment by taurus-forever** [comment]
> @taurus-forever can you clarify which branch this should be going into and why the default doesnt seem to be in line with `8.0_22.04`?

Short: please commit it into `8.0-20.04`.

Long: 
* there is no branch `8.0-22.04` right now, as we build series `focal` only. We should start building `jammy` ASAP to relate with modern jammy-based applications.
* mysql-router charm is a subordinate one. We will have to build/support `mysql-router-container` as `chamred-mysql-container` will be to big for subordinate VM installation.
* `main` is out of sync with  `8.0-20.04` due to historical reason. IMHO, `main` should exist and contains README.md+CI/CD only. Let's discuss this in a sync today.
* the branch `8.0-20.04` ~matches to Docker tag, but doesn't match our common naming logic `8.0/edge`. Is `docker-compose` planned for rockcraft? :-D IMHO it is easier to support branch `8.0/edge` with subfolders, e.g.
```
20.04/rockcraft.yaml
22.04/rockcraft.yaml
```
Good ideas are welcome!

**Comment by jardon** [comment]
This is one reason that I don't like the idea of naming the default branch as `main` as its not descriptive at all.  

Having separate versions in subfolders makes things simple, but it also has the ability to make things messy.  I try to let version control systems do what they do.

**Review by taurus-forever — APPROVED** [review]
LGTM, please address Carl' comments. Tnx!

**Review by taurus-forever — APPROVED** [review]

**Pull request merged**
