### PR TITLE
Move mysql-router to GHCR

### PR DESCRIPTION
**Pull request by jardon**
## Issue
mysql-router is being published to Docker hub and needs to be moved to GHCR

## Solution
Update the publishing pipeline to push to GHCR

### CODE REVIEW

**Review by shayancanonical — COMMENTED** [review]
We are planning on using the `charmed-mysql` rock in mysql-router-k8s, and so am wondering if we should be archiving this repository?

**Comment by jardon** [comment]
> We are planning on using the `charmed-mysql` rock in mysql-router-k8s, and so am wondering if we should be archiving this repository?

That is a question for @taurus-forever

**Comment by paulomach** [comment]
> > We are planning on using the `charmed-mysql` rock in mysql-router-k8s, and so am wondering if we should be archiving this repository?
> 
> That is a question for @taurus-forever

Do we have a final word on this Alex?

**Review by taurus-forever — APPROVED** [review]
Tnx!

**Review by paulomach — APPROVED** [review]

**Pull request merged**
